version: "3"
services:
  nginx:
    build: ./nginx
    restart: unless-stopped
    volumes:
      - ./data/certs:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"
    networks:
      - next-express
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecom
    networks:
      - database
  cache:
    image: redis
    networks:
      - database
  client:
    build: ./client
    depends_on:
      - server
    networks:
      - next-express
    expose:
      - 3000
  server:
    build: ./server
    networks:
      - next-express
      - database
    depends_on:
      - db
      - cache
    ports:
      - '3001:3001'
    expose:
      - 3001
      - 8001
networks:
  next-express: {}
  database: {}
