version: '3.9'

services:
  db:
    image: postgres:13
    restart: always
    container_name: integration-tests-postgres
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tests
  # redis:
  #   image: redis
  #   container_name: intergration-tests-redis
  #   ports:
  #     - '6380:6379'